[theme]
background = 0x99000000
accent = 0xFF004400
secondary_accent = 0xFF007700
base = 0xFF007700
alt_base = 0xFF004400

[Arc Theme]
--background = 0x99000000
--accent = 0xFFC159FF
--secondary_accent = 0xCCC159FF
--base = 0xCC159FF
--alt_base = 0xFFC159FF
